# Generated by Django 3.1.3 on 2020-11-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(db_column='position', on_delete=django.db.models.deletion.CASCADE, to='users.position'),
        ),
    ]
